//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiREV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database.mdf;" +
            "Integrated Security=True")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280, 800")]
        public global::System.Drawing.Point MainLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainLocation"]));
            }
            set {
                this["MainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280, 1")]
        public global::System.Drawing.Point ImgCentLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImgCentLocation"]));
            }
            set {
                this["ImgCentLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1302, 776")]
        public global::System.Drawing.Size ImgCentSize {
            get {
                return ((global::System.Drawing.Size)(this["ImgCentSize"]));
            }
            set {
                this["ImgCentSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 1")]
        public global::System.Drawing.Point ImgLeftLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImgLeftLocation"]));
            }
            set {
                this["ImgLeftLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1302, 776")]
        public global::System.Drawing.Size ImgLeftSize {
            get {
                return ((global::System.Drawing.Size)(this["ImgLeftSize"]));
            }
            set {
                this["ImgLeftSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2560, 1")]
        public global::System.Drawing.Point ImgRghtLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImgRghtLocation"]));
            }
            set {
                this["ImgRghtLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1302, 776")]
        public global::System.Drawing.Size ImgRghtSize {
            get {
                return ((global::System.Drawing.Size)(this["ImgRghtSize"]));
            }
            set {
                this["ImgRghtSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 760")]
        public global::System.Drawing.Point MapLocation {
            get {
                return ((global::System.Drawing.Point)(this["MapLocation"]));
            }
            set {
                this["MapLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280, 1280")]
        public global::System.Drawing.Size MapSize {
            get {
                return ((global::System.Drawing.Size)(this["MapSize"]));
            }
            set {
                this["MapSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2840, 320")]
        public global::System.Drawing.Point CodeLocation {
            get {
                return ((global::System.Drawing.Point)(this["CodeLocation"]));
            }
            set {
                this["CodeLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("596, 1560")]
        public global::System.Drawing.Size CodeSize {
            get {
                return ((global::System.Drawing.Size)(this["CodeSize"]));
            }
            set {
                this["CodeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ScreenRatio {
            get {
                return ((double)(this["ScreenRatio"]));
            }
            set {
                this["ScreenRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("398, 918")]
        public global::System.Drawing.Size IncGaugSize {
            get {
                return ((global::System.Drawing.Size)(this["IncGaugSize"]));
            }
            set {
                this["IncGaugSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point IncGaugLocation {
            get {
                return ((global::System.Drawing.Point)(this["IncGaugLocation"]));
            }
            set {
                this["IncGaugLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2392, 21")]
        public global::System.Drawing.Size RadiusSize {
            get {
                return ((global::System.Drawing.Size)(this["RadiusSize"]));
            }
            set {
                this["RadiusSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RadiusLocation {
            get {
                return ((global::System.Drawing.Point)(this["RadiusLocation"]));
            }
            set {
                this["RadiusLocation"] = value;
            }
        }
    }
}
